sudo: required

language: java

branches:
  only:
    - master

env:
  global:
    - "COMMIT=${TRAVIS_COMMIT::8}"
    - "REPO=ezh1k/exim"
    - "TAG=$(if [ \"$TRAVIS_BRANCH\" == \"master\" ]; then echo \"latest\"; else echo $TRAVIS_BRANCH ; fi)"
    - "GIT_TAG=$(git describe --always)"
    - "DOCKER_VERSION=1.12.3"
    - "DOCKER_COMPOSE_VERSION=1.8.1"

services:
  - docker

before-install:
  - |
    sudo rm /usr/local/bin/docker-compose
    curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin
    # check docker versions
    docker version
    docker-compose version

before_script:
  - |
    set -e
    openssl aes-256-cbc -K $encrypted_b04a9de20608_key -iv $encrypted_b04a9de20608_iv -in .dockerhub.enc -out .dockerhub -d
    sh .dockerhub

script:
  - |
    set -e
    docker images
    echo -e "\e[0;33mBuild docker image REPO:$REPO COMMIT:$COMMIT TAG:$TAG GIT_TAG:$GIT_TAG BUILD_NUMBER:$TRAVIS_BUILD_NUMBER\e[m" && echo -en 'travis_fold:start:build\\r'
    docker-compose -f docker-compose.yml -f docker-compose.travis.yml up -d
    echo -en 'travis_fold:end:build\\r'
    sleep 5
    docker-compose exec exim /bin/bash -c 'ps aux | awk "/^exim.*q15m/ {print \"TEST PASSED\"}"' | grep PASSED
    docker-compose down
    docker tag exim:latest $REPO
    docker tag $REPO $REPO:$TAG

after_success:
  - |
    set -e
    docker images
    if [ "$TRAVIS_SECURE_ENV_VARS" = "true" -a  "$TRAVIS_PULL_REQUEST" == "false" ]; then
      [[ "$TAG" != "latest" ]] && docker push $REPO
    fi

